=== openmainframeproject/zorow/provisioning-workflows/WAS/actions_v1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:element name="actionList">
		<xs:complexType>
			<xs:sequence>
				<!-- Action element is not optional. Maximum occurrence is 50 elements. -->
				<xs:element name="action" type="actionType" minOccurs="1" maxOccurs="50" />
			</xs:sequence>
		</xs:complexType>
		
		<xs:unique name="uniqueActionName">
			<xs:selector xpath="action" />
			<xs:field xpath="@name" />
		</xs:unique>
	</xs:element>
	
	<xs:complexType name="actionType">
		<xs:sequence>
			<!-- List of action types. -->
			<xs:choice>
				<xs:element name="command" type="actionCommandType" />
				<xs:element name="workflow" type="actionWorkflowType">
					<xs:unique name="uniqueWfVarName">
						<xs:selector xpath="wfVar" />
						<xs:field xpath="@name" />
					</xs:unique>
				</xs:element>
				<xs:element name="instructions" type="velocityNonNullString" />
			</xs:choice>
		</xs:sequence>
		<!-- Action name attribute is not optional. -->
		<xs:attribute name="name" type="actionNameType" use="required" />
	</xs:complexType>
	
	<!-- Elements specific to action type - command -->
	<xs:complexType name="actionCommandType">
		<xs:sequence>			
			<!-- Stores the actual command. Required. -->
			<xs:element name="commandValue" type="velocityNonNullString" minOccurs="1" maxOccurs="1" />
			
			<!-- runAsUser is optional. -->
			<xs:element name="runAsUser" type="runAsUserType" minOccurs="0" maxOccurs="1" />
						
			<!-- Stores the solKey. Optional. -->
			<xs:element name="solKey" type="velocityNonNullString" minOccurs="0" maxOccurs="1" />
			
			<!-- Stores the unsolKey. Optional. -->
			<xs:element name="unsolKey" type="velocityNonNullString" minOccurs="0" maxOccurs="1" />
			
			<!-- Stores the detectTime. Optional.  The units are in seconds. -->
			<xs:element name="detectTime" type="velocityNonNullString" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	
	<!-- Elements and attributes specific to action type - workflow. -->
	<xs:complexType name="actionWorkflowType">
		<xs:sequence>
			<!-- Action workflow definition file is not optional. -->
			<xs:element name="wfDefFile" type="filepathNonNull" />

			<!-- Action workflow variable input file. -->
			<xs:element name="wfVarInFile" type="filepathNull" minOccurs="0" maxOccurs="1" />

			<!-- Action workflow variable(s). Maximum occurrence is 1,500 variables. -->
			<xs:element name="wfVar" type="varType" minOccurs="0" maxOccurs="1500" />
		</xs:sequence>
		<!-- Figure out a way to differentiate z/OS and UNIX -->
	</xs:complexType>
	
	<!--
		velocityString extends xs:string (via the intermediary bigString) to add a 
		"substitution=" attribute.  It's important that this type allow a null string.
	-->
	<xs:complexType name="velocityString" mixed="true">
		<xs:simpleContent>
			<xs:extension base="bigString">
				<!-- Indicates substitution variables are present. -->
				<xs:attribute name="substitution" type="actionBooleanType" default="false"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<!-- 
		velocityNonNullString extends velocityString to add a restriction, preventing
		null values, or one that contains only whitespaces.
	-->
	<xs:complexType name="velocityNonNullString">
		<xs:simpleContent>
			<xs:restriction base="velocityString">
				<xs:minLength value="1" />
				<xs:whiteSpace value="collapse" />
			</xs:restriction>
		</xs:simpleContent>
	</xs:complexType>
	
	<!--
		This type provides a substitution option for variables,
		and prevents a null value.
	-->
	<xs:complexType name="runAsUserType">
		<xs:simpleContent>		
			<xs:extension base="nonNullString">		    
				<!-- Indicates substitution variables are present. -->
				<xs:attribute name= "substitution" type="actionBooleanType" default="false"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<!--
		Elements and attributes specific to workflow variables.
	-->
	<xs:complexType name="varType">
		<xs:simpleContent>
			<xs:extension base="velocityString">
				<xs:attribute name="name" type="varNameType" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<!--
		This type allows an alphanumeric value, prevents a null value
		including one that only contains only whitespace,
		and establishes a maximum of 32 characters.
	-->
	<xs:simpleType name="actionNameType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z][a-zA-Z0-9\-_]*" />
			<xs:minLength value="1" />
			<xs:maxLength value="32" />
			<xs:whiteSpace value="collapse" />
		</xs:restriction>
	</xs:simpleType>
	
	<!--
		This type allows a null value, preserves whitespace,
		and establishes a maximum length of 1,000,000 characters.
	-->
	<xs:simpleType name="bigString">
		<xs:restriction base="xs:string">
			<xs:maxLength value="1000000" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="nonNullString">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
		</xs:restriction>
	</xs:simpleType>
	
	<!-- We define our own boolean type to protect against values of "0" and "1". --> 
	<xs:simpleType name="actionBooleanType">
  		<xs:restriction base="xs:string">
  			<xs:enumeration value="true"/>
    		<xs:enumeration value="false"/>
  		</xs:restriction>
	</xs:simpleType>
	
	<!--
		This type prevents a null value, and establishes a maximum length of
		1,024 characters.
	-->
	<xs:simpleType name="filepathNonNull">
		<xs:restriction base="xs:string">
			<xs:minLength value="1" />
			<xs:maxLength value="1024" />
		</xs:restriction>
	</xs:simpleType>
	
	<!--
		This type establishes a maximum length of 1,024 characters.
	-->
	<xs:simpleType name="filepathNull">
		<xs:restriction base="xs:string">
			<xs:minLength value="0" />
			<xs:maxLength value="1024" />
		</xs:restriction>
	</xs:simpleType>
	
	<!--
		Variable name: Simple alphaNumeric national and "_" string type used
		for variable names. This restriction allows us to specify variable
		names with their scope as a string with colon delimiter. scope:name.
		If the ":" could appear as part of the variable name it increases the
		chance for error.
	-->
	<xs:simpleType name="varNameType">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z][a-zA-Z0-9\-_]*" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== openmainframeproject/zorow/provisioning-workflows/WAS/workflows/actions.xml
<?xml version="1.0" encoding="utf-8"?>
<actionList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:noNamespaceSchemaLocation="./actions_v1.xsd">
  <action name="deprovision">
		<workflow>
			<wfDefFile>./deprovision.xml</wfDefFile>
			<wfVarInFile>../properties/server_group_variables.properties</wfVarInFile>
			<wfVar name="SERVER_ID_NUM">${SERVER_ID_NUM}</wfVar>
		</workflow>
  </action>
  <action name="startServer">
    <command>
      <commandValue>START ${SERVER_GROUP_PREFIX}CR${SERVER_ID_NUM},JOBNAME=${SERVER_GROUP_PREFIX}${SERVER_ID_NUM}S1,ENV=${SERVER_GROUP_PREFIX}${SERVER_ID_NUM}.${SERVER_GROUP_PREFIX}${SERVER_ID_NUM}.${SERVER_GROUP_PREFIX}${SERVER_ID_NUM}S1,REUSASID=YES
      </commandValue>
      <runAsUser substitution="true">$!{CONSOLE_USER}</runAsUser>
      <approver substitution="true">$!{CONSOLE_APPROVER}</approver>
      <unsolKey>BBOO0247I</unsolKey>
      <detectTime>120</detectTime>
    </command>
  </action>
  <action name="stopServer">
    <command>
      <commandValue>P ${SERVER_GROUP_PREFIX}${SERVER_ID_NUM}DM
      </commandValue>
      <runAsUser substitution="true">$!{CONSOLE_USER}</runAsUser>
      <approver substitution="true">$!{CONSOLE_APPROVER}</approver>
      <unsolKey>BBOO0008I</unsolKey>
      <detectTime>120</detectTime>
    </command>
  </action>
  <action name="createType2JDBC">
		<workflow>
			<wfDefFile>./createDB2Type2.xml</wfDefFile>
			<wfVarInFile>../properties/server_group_variables.properties</wfVarInFile>
			<wfVar name="SERVER_ID_NUM">${SERVER_ID_NUM}</wfVar>
		</workflow>
  </action>
  <action name="createType4JDBC">
		<workflow>
			<wfDefFile>./createDB2Type4.xml</wfDefFile>
			<wfVarInFile>../properties/server_group_variables.properties</wfVarInFile>
			<wfVar name="SERVER_ID_NUM">${SERVER_ID_NUM}</wfVar>
		</workflow>
  </action>
</actionList>

=== openmainframeproject/zorow/provisioning-workflows/WLP/workflows/actions.xml
<?xml version="1.0" encoding="utf-8"?>
<actionList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:noNamespaceSchemaLocation="./actions_v1.xsd">
	<action name="stop">
		<workflow>
			<wfDefFile>./stopServer.xml</wfDefFile>
			<wfVarInFile>../properties/workflow_variables.properties</wfVarInFile>
			<!-- Obtain values for the properties from
			the registry entry associated with the provisioning
			workflow. -->
			<wfVar name="WLP_USER">${WLP_USER}</wfVar>
			<wfVar name="WLP_USER_DIR">${WLP_USER_DIR}</wfVar>
			<wfVar name="WLP_INSTALL_DIR">${WLP_INSTALL_DIR}</wfVar>
			<wfVar name="JAVA_HOME">${JAVA_HOME}</wfVar>
			<wfVar name="START_SERVER_AS_STARTED_TASK">${START_SERVER_AS_STARTED_TASK}</wfVar>
			<wfVar name="PROCLIB">${PROCLIB}</wfVar>
			<wfVar name="CONSOLE_NAME">${CONSOLE_NAME}</wfVar>
		</workflow>
	</action>
	<action name="start">
		<workflow>
			<wfDefFile>./startServer.xml</wfDefFile>
			<wfVarInFile>../properties/workflow_variables.properties</wfVarInFile>
			<!-- Obtain values for the properties from
			the registry entry associated with the provisioning
			workflow. -->
			<wfVar name="WLP_USER">${WLP_USER}</wfVar>
			<wfVar name="WLP_USER_DIR">${WLP_USER_DIR}</wfVar>
			<wfVar name="WLP_INSTALL_DIR">${WLP_INSTALL_DIR}</wfVar>
			<wfVar name="JAVA_HOME">${JAVA_HOME}</wfVar>
			<wfVar name="START_SERVER_AS_STARTED_TASK">${START_SERVER_AS_STARTED_TASK}</wfVar>
			<wfVar name="PROCLIB">${PROCLIB}</wfVar>
			<wfVar name="CONSOLE_NAME">${CONSOLE_NAME}</wfVar>
		</workflow>
	</action>
	<action name="db2Bind">
		<workflow>
			<wfDefFile>./db2Bind.xml</wfDefFile>
			<wfVarInFile>../properties/workflow_variables.properties</wfVarInFile>
			<!-- Obtain values for the properties from
			the registry entry associated with the provisioning
			workflow. -->
			<wfVar name="WLP_USER">${WLP_USER}</wfVar>
			<wfVar name="WLP_USER_DIR">${WLP_USER_DIR}</wfVar>
			<wfVar name="DB2_REGISTRY_NAME">${DB2_REGISTRY_NAME}</wfVar>
			<wfVar name="WLP_INSTALL_DIR">${WLP_INSTALL_DIR}</wfVar>
			<wfVar name="JAVA_HOME">${JAVA_HOME}</wfVar>
			<wfVar name="PROCLIB">${PROCLIB}</wfVar>
			<wfVar name="START_SERVER_AS_STARTED_TASK">${START_SERVER_AS_STARTED_TASK}</wfVar>
		    <wfVar name="DB2_CONNECTION_TYPE">${DB2_CONNECTION_TYPE}</wfVar>
		    <wfVar name="CONSOLE_NAME">${CONSOLE_NAME}</wfVar>
		</workflow>
	</action>
	<action name="db2Unbind">
		<workflow>
			<wfDefFile>./db2Unbind.xml</wfDefFile>
			<wfVarInFile>../properties/workflow_variables.properties</wfVarInFile>
			<!-- Obtain values for the properties from
			the registry entry associated with the provisioning
			workflow. -->
			<wfVar name="WLP_USER">${WLP_USER}</wfVar>
			<wfVar name="WLP_USER_DIR">${WLP_USER_DIR}</wfVar>
			<wfVar name="DB2_REGISTRY_NAME">${DB2_REGISTRY_NAME}</wfVar>
			<wfVar name="WLP_INSTALL_DIR">${WLP_INSTALL_DIR}</wfVar>
			<wfVar name="JAVA_HOME">${JAVA_HOME}</wfVar>
			<wfVar name="PROCLIB">${PROCLIB}</wfVar>
			<wfVar name="START_SERVER_AS_STARTED_TASK">${START_SERVER_AS_STARTED_TASK}</wfVar>
		    <wfVar name="CONSOLE_NAME">${CONSOLE_NAME}</wfVar>
		</workflow>
	</action>
	<action name="checkStatus">
		<workflow>
			<wfDefFile>./checkStatus.xml</wfDefFile>
			<wfVarInFile>../properties/workflow_variables.properties</wfVarInFile>
			<!-- Obtain values for the properties from
			the registry entry associated with the provisioning
			workflow. -->
			<wfVar name="WLP_INSTALL_DIR">${WLP_INSTALL_DIR}</wfVar>
			<wfVar name="WLP_USER_DIR">${WLP_USER_DIR}</wfVar>
			<wfVar name="JAVA_HOME">${JAVA_HOME}</wfVar>
			<wfVar name="START_SERVER_AS_STARTED_TASK">${START_SERVER_AS_STARTED_TASK}</wfVar>
			<wfVar name="CONSOLE_NAME">${CONSOLE_NAME}</wfVar>
			<wfVar name="SERVER_STOPPED">${SERVER_STOPPED}</wfVar>
		</workflow>
	</action>
	<action name="deprovision">
		<workflow>
			<wfDefFile>./deprovision.xml</wfDefFile>
			<wfVarInFile>../properties/workflow_variables.properties</wfVarInFile>
			<!-- Obtain values for the properties from
			the registry entry associated with the provisioning
			workflow. -->
			<wfVar name="WLP_USER">${WLP_USER}</wfVar>
			<wfVar name="WLP_USER_DIR">${WLP_USER_DIR}</wfVar>
			<wfVar name="DB2_REGISTRY_NAME">${DB2_REGISTRY_NAME}</wfVar>
			<wfVar name="WLP_INSTALL_DIR">${WLP_INSTALL_DIR}</wfVar>
			<wfVar name="JAVA_HOME">${JAVA_HOME}</wfVar>
			<wfVar name="WLP_ENABLE_SSL_SAF_CERTIFICATES">${WLP_ENABLE_SSL_SAF_CERTIFICATES}</wfVar>
			<wfVar name="START_SERVER_AS_STARTED_TASK">${START_SERVER_AS_STARTED_TASK}</wfVar>
			<wfVar name="PROCLIB">${PROCLIB}</wfVar>
			<wfVar name="HTTP_PORT_ID">${HTTP_PORT_ID}</wfVar>
			<wfVar name="HTTPS_PORT_ID">${HTTPS_PORT_ID}</wfVar>
			<wfVar name="CLASSIFICATION_RULE_ID">${CLASSIFICATION_RULE_ID}</wfVar>
			<wfVar name="IP_ADDRESS_ID">${IP_ADDRESS_ID}</wfVar>
			<wfVar name="WLP_CREATE_ZFS">${WLP_CREATE_ZFS}</wfVar>
			<wfVar name="VOLUME">${VOLUME}</wfVar>
			<wfVar name="CONSOLE_NAME">${CONSOLE_NAME}</wfVar>
		</workflow>
	</action>
</actionList>
